service: radioGalegaAlexa

custom:
  region: eu-west-1
  stage: dev

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'default'}
  region: eu-west-1
  logRetentionInDays: 1
  role: radioGalegaAlexa

package: # Optional deployment packaging configuration
  include:
    - "lambda/py/**"
  exclude:
    - '**'

resources:
  radioGalegaAlexa:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: radio_galega_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: radio_galega_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'

functions:
  radioGalegaSkill:
    handler: lambda_function.lambda_handler
    events:
      - alexaSkill: amzn1.ask.skill.7ff19e3d-a21e-4b3b-bfe3-11b8f9bc273b
