service: radioGalegaAlexa

provider:
  name: aws
  runtime: python3.7
  region: eu-west-1

plugins:
  - serverless-python-requirements
  - serverless-s3-deploy

custom:
  s3AssetsBucket: alexa-radio-galega-assets
  pythonRequirements:
    dockerizePip: non-linux
  assets:
    targets:
      - bucket: ${self:custom.s3AssetsBucket}
        files:
          - source: ../..
            globs: "*.jpg"
      - bucket: ${self:custom.s3AssetsBucket}
        files:
          - source: ../..
            globs: "*.m3u"

resources:
  Resources:
    S3RadioGalega:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3AssetsBucket}
        AccessControl: PublicRead

package:
  exclude:
    - node_modules

functions:
  radioGalegaSkill:
    handler: lambda_function.lambda_handler
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.7ff19e3d-a21e-4b3b-bfe3-11b8f9bc273b
          enabled: true
